# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cognitive.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cognitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ognitive.proto\x12\x07openbad\x1a\x0c\x63ommon.proto\"\xa8\x01\n\x11\x45scalationRequest\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x13\n\x0b\x65vent_topic\x18\x02 \x01(\t\x12\x15\n\revent_payload\x18\x03 \x01(\x0c\x12\x0e\n\x06reason\x18\x04 \x01(\t\x12#\n\x08priority\x18\x05 \x01(\x0e\x32\x11.openbad.Priority\x12\x11\n\treflex_id\x18\x06 \x01(\t\"\xa1\x01\n\x0f\x43ognitiveResult\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x16\n\x0e\x63orrelation_id\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x03 \x01(\t\x12\x16\n\x0e\x61\x63tion_payload\x18\x04 \x01(\x0c\x12\x12\n\nmodel_used\x18\x05 \x01(\t\x12\x17\n\x0ftokens_consumed\x18\x06 \x01(\x04\"\xb0\x01\n\x10ReasoningRequest\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontext_tokens\x18\x03 \x01(\r\x12#\n\x08priority\x18\x04 \x01(\x0e\x32\x11.openbad.Priority\x12\x1a\n\x12preferred_provider\x18\x05 \x01(\t\x12\x12\n\nmax_tokens\x18\x06 \x01(\r\"\xad\x01\n\x11ReasoningResponse\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\nmodel_used\x18\x03 \x01(\t\x12\x10\n\x08provider\x18\x04 \x01(\t\x12\x13\n\x0btokens_used\x18\x05 \x01(\r\x12\x12\n\nlatency_ms\x18\x06 \x01(\x01\x12\x17\n\x0freasoning_trace\x18\x07 \x01(\t\"\x95\x01\n\x11ModelHealthStatus\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x11\n\tavailable\x18\x04 \x01(\x08\x12\x13\n\x0blatency_p50\x18\x05 \x01(\x01\x12\x13\n\x0blatency_p99\x18\x06 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cognitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESCALATIONREQUEST']._serialized_start=43
  _globals['_ESCALATIONREQUEST']._serialized_end=211
  _globals['_COGNITIVERESULT']._serialized_start=214
  _globals['_COGNITIVERESULT']._serialized_end=375
  _globals['_REASONINGREQUEST']._serialized_start=378
  _globals['_REASONINGREQUEST']._serialized_end=554
  _globals['_REASONINGRESPONSE']._serialized_start=557
  _globals['_REASONINGRESPONSE']._serialized_end=730
  _globals['_MODELHEALTHSTATUS']._serialized_start=733
  _globals['_MODELHEALTHSTATUS']._serialized_end=882
# @@protoc_insertion_point(module_scope)
