# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: endocrine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'endocrine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65ndocrine.proto\x12\x07openbad\x1a\x0c\x63ommon.proto\"\xbd\x01\n\x0e\x45ndocrineEvent\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x0f\n\x07hormone\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\x01\x12#\n\x08severity\x18\x04 \x01(\x0e\x32\x11.openbad.Severity\x12\x13\n\x0bmetric_name\x18\x05 \x01(\t\x12\x14\n\x0cmetric_value\x18\x06 \x01(\x01\x12\x1a\n\x12recommended_action\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'endocrine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENDOCRINEEVENT']._serialized_start=43
  _globals['_ENDOCRINEEVENT']._serialized_end=232
# @@protoc_insertion_point(module_scope)
