# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: immune.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'immune.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimmune.proto\x12\x07openbad\x1a\x0c\x63ommon.proto\"\x9d\x01\n\x0bImmuneAlert\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12#\n\x08severity\x18\x02 \x01(\x0e\x32\x11.openbad.Severity\x12\x13\n\x0bthreat_type\x18\x03 \x01(\t\x12\x11\n\tsource_id\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x05 \x01(\t\x12\x10\n\x08\x65vidence\x18\x06 \x01(\x0c\"\x8a\x01\n\x0fQuarantineEvent\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63tion_taken\x18\x04 \x01(\t\x12\x1d\n\x15quarantine_until_unix\x18\x05 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'immune_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMMUNEALERT']._serialized_start=40
  _globals['_IMMUNEALERT']._serialized_end=197
  _globals['_QUARANTINEEVENT']._serialized_start=200
  _globals['_QUARANTINEEVENT']._serialized_end=338
# @@protoc_insertion_point(module_scope)
