# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reflex.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'reflex.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creflex.proto\x12\x07openbad\x1a\x0c\x63ommon.proto\"\x94\x01\n\rReflexTrigger\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x11\n\treflex_id\x18\x02 \x01(\t\x12\x13\n\x0b\x65vent_topic\x18\x03 \x01(\t\x12\x15\n\revent_payload\x18\x04 \x01(\x0c\x12#\n\x08severity\x18\x05 \x01(\x0e\x32\x11.openbad.Severity\"\x8b\x01\n\x0cReflexResult\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x11\n\treflex_id\x18\x02 \x01(\t\x12\x0f\n\x07handled\x18\x03 \x01(\x08\x12\x14\n\x0c\x61\x63tion_taken\x18\x04 \x01(\t\x12\x11\n\tescalated\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"t\n\x0bReflexState\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x16\n\x0eprevious_state\x18\x02 \x01(\t\x12\x15\n\rcurrent_state\x18\x03 \x01(\t\x12\x15\n\rtrigger_event\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reflex_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFLEXTRIGGER']._serialized_start=40
  _globals['_REFLEXTRIGGER']._serialized_end=188
  _globals['_REFLEXRESULT']._serialized_start=191
  _globals['_REFLEXRESULT']._serialized_end=330
  _globals['_REFLEXSTATE']._serialized_start=332
  _globals['_REFLEXSTATE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
