# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x07openbad\x1a\x0c\x63ommon.proto\"\x9d\x01\n\x0c\x43puTelemetry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x15\n\rusage_percent\x18\x02 \x01(\x01\x12\x16\n\x0esystem_percent\x18\x03 \x01(\x01\x12\x14\n\x0cuser_percent\x18\x04 \x01(\x01\x12\x12\n\ncore_count\x18\x05 \x01(\r\x12\x13\n\x0bload_avg_1m\x18\x06 \x01(\x01\"\xa1\x01\n\x0fMemoryTelemetry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x15\n\rusage_percent\x18\x02 \x01(\x01\x12\x12\n\nused_bytes\x18\x03 \x01(\x04\x12\x13\n\x0btotal_bytes\x18\x04 \x01(\x04\x12\x17\n\x0f\x61vailable_bytes\x18\x05 \x01(\x04\x12\x14\n\x0cswap_percent\x18\x06 \x01(\x01\"\x9b\x01\n\rDiskTelemetry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x15\n\rusage_percent\x18\x02 \x01(\x01\x12\x12\n\nread_bytes\x18\x03 \x01(\x04\x12\x13\n\x0bwrite_bytes\x18\x04 \x01(\x04\x12\x15\n\rio_latency_ms\x18\x05 \x01(\x01\x12\x12\n\nfree_bytes\x18\x06 \x01(\x04\"\xad\x01\n\x0eTokenTelemetry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x13\n\x0btokens_used\x18\x02 \x01(\x04\x12\x16\n\x0e\x62udget_ceiling\x18\x03 \x01(\x04\x12\x1c\n\x14\x62udget_remaining_pct\x18\x04 \x01(\x01\x12\x1b\n\x13\x63ost_per_action_avg\x18\x05 \x01(\x01\x12\x12\n\nmodel_tier\x18\x06 \x01(\t\"\x87\x01\n\x10NetworkTelemetry\x12\x1f\n\x06header\x18\x01 \x01(\x0b\x32\x0f.openbad.Header\x12\x12\n\nbytes_sent\x18\x02 \x01(\x04\x12\x12\n\nbytes_recv\x18\x03 \x01(\x04\x12\x14\n\x0cpackets_sent\x18\x04 \x01(\x04\x12\x14\n\x0cpackets_recv\x18\x05 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CPUTELEMETRY']._serialized_start=43
  _globals['_CPUTELEMETRY']._serialized_end=200
  _globals['_MEMORYTELEMETRY']._serialized_start=203
  _globals['_MEMORYTELEMETRY']._serialized_end=364
  _globals['_DISKTELEMETRY']._serialized_start=367
  _globals['_DISKTELEMETRY']._serialized_end=522
  _globals['_TOKENTELEMETRY']._serialized_start=525
  _globals['_TOKENTELEMETRY']._serialized_end=698
  _globals['_NETWORKTELEMETRY']._serialized_start=701
  _globals['_NETWORKTELEMETRY']._serialized_end=836
# @@protoc_insertion_point(module_scope)
